# Generated by Django 5.2.6 on 2025-09-20 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('date_publication', models.DateField()),
                ('auteur', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OffreEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('localisation', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('profil_recherche', models.TextField()),
                ('date_limite', models.DateField()),
                ('slug', models.SlugField(unique=True)),
                ('publie', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('contenu', models.TextField()),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True)),
                ('cv', models.FileField(upload_to='cvs/')),
                ('date_postulation', models.DateTimeField(auto_now_add=True)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='core.offreemploi')),
            ],
        ),
    ]
