# Generated by Django 5.2.6 on 2025-09-20 03:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='auteur',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='date_publication',
        ),
        migrations.AddField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='titre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.offreemploi'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
    ]
